steps:
  - name: 'gcr.io/buildpacks/builder'
    args:
      - 'build'
      - 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=staging'

images:
  - 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
